# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4f2ffc04a4e9ac2f20f1cf6636622089d23d634f975913ed72fe569f0a1cae72cd8a0693d215d3ece42adcf7b391261424774824b086398a02d2864991c7a20

test:
  secret_key_base: 0e84c539e809cca5495c19bd1322252c6f70be7523ead7c37a6c69b9bb6360f4a691502be8195c621e533d6f2cb77c585797b79dfe74c3b79e9da20ce65949ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
